server:
  port: 9000
spring:
  profiles:
    active: local
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: net.ferrum.book.entity
    configuration:
      map-underscore-to-camel-case: true
      log-prefix: "[SQL-debug] ->"
      log-impl: SLF4J
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 60000
      keepalive-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      connection-test-query: SELECT 1
